<?php

// TODO configure URL rules with autogenerated spec rules

return [
    '' => 'site/index',
    
    // default URLs for making existing controllers available
    '<controller>' => '<controller>/index',
    '<controller>/<action>' => '<controller>/<action>',
];
