#!/usr/bin/env php
<?php

require(__DIR__ . '/config/env.php');

$config = require(__DIR__ . '/console/config/app-' . YII_ENV . '.php');

$app = new yii\console\Application($config);
$exitCode = $app->run();
exit($exitCode);
