<?php

// TODO configure URL rules with autogenerated spec rules

return [
    '' => 'home/index',
    [
        'class' => yii\rest\UrlRule::class,
        'controller' => ['home'],
        'pluralize' => false,
        'extraPatterns' => [
            'GET index' => 'index'
        ]
    ]
];
